### ISSUE TITLE
Proofreading Bugs on iPad

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Quill-Grammar#151]
@kriskelly @wlaurance @petergault 

Encountered a few issues when attempting to load proofreading on an iPad.

1. Activity shows white for a long time, no passage loads.

![img_0183](https://cloud.githubusercontent.com/assets/12731246/9639124/4b5a53e2-515f-11e5-8a28-1d9dfe18f18d.PNG)

2. When activity does load, it gets stuck at the bottom of the page and does not allow for editing.

![img_0184](https://cloud.githubusercontent.com/assets/12731246/9639135/61cf1914-515f-11e5-94c5-fc61310c3d5e.PNG)
![img_0185](https://cloud.githubusercontent.com/assets/12731246/9639145/6f298c3e-515f-11e5-8f23-d80fb2066197.PNG)

3. Eventually the page does load properly and allows for editing.

![img_0186](https://cloud.githubusercontent.com/assets/12731246/9639149/7a047c5e-515f-11e5-932a-c19a3e343061.PNG)

**Comment by kriskelly** [comment]
Just a guess, but it sounds like this is not an iPad bug so much as a performance issue. Hard to say without looking more in depth, but the fact that it eventually does work seems to indicate that it's just slow on iPads.

**Comment by wlaurance** [comment]
I wonder if the web socket firebase connections are more expensive to setup
than desktop.

**Comment by wlaurance** [comment]
https://www.binpress.com/tutorial/speeding-up-angular-js-with-simple-optimizations/135

This particular page incurs a ton of digest cycles because each individual word as an angular controlled input box.

We may need to move the input boxes to pure DOM elements instead of angular. Like @kriskelly said, because it eventually works, this is likely a performance issue.

My earlier comment is kinda void because it is only one websocket connection made to firebase. All of the other requests are HTTP. So if this is continuously an issue, the likely case is an abused digest cycle, and a computer (ipad processors) unable to render the content effectively.

**Comment by wlaurance** [comment]
Another optimizations blog entry that could be useful http://blog.scalyr.com/2013/10/angularjs-1200ms-to-35ms/

**Comment by kriskelly** [comment]
@wlaurance Do you have an approach in mind for converting the input boxes to DOM elements? I remember it being sort of annoying to try to integrate non-Angular vanilla JS into angular apps, but it could definitely help a lot. The `ng-repeat` for each word seems to be the big offender, all the blog posts I've read online say not to use it.

**Comment by wlaurance** [comment]
Maybe there is a more efficient ng repeat directive we can use.

We should confirm this is the issue by replacing this html with a simple
paragraph and see if the render time on iPad decreases.

**Comment by kriskelly** [comment]
I found this: https://github.com/allaud/quick-ng-repeat Currently trying it out on staging.

**Comment by kriskelly** [comment]
It doesn't seem to help at all with the load times on staging. Btw I'm using BrowserStack's iPad 4th gen emulator, which seems to repro the slow load times.

**Comment by kriskelly** [comment]
@wlaurance @petergault @elliotmandel Also something funny i've noticed is that iPad safari seems to have spell check enabled, so you end up seeing the standard dotted red underlines under misspelled words anyway.

**Comment by kriskelly** [comment]
@wlaurance It might be taking awhile to load the actual JS for the site. I was profiling and it seemed like we can do a few things to speed that up, namely: gzip the files in the build pipeline, also loading 'optional' JS like Typekit in an async fashion should speed page loads somewhat.

**Comment by wlaurance** [comment]
On staging, none of the files run through optimizations. No minification etc. But the performance hit happens on production as well.

**Comment by kriskelly** [comment]
Yeah looks like Firebase hosting is Gzipping the JS files anyway so no need to deal with that ourselves.

**Comment by kriskelly** [comment]
@wlaurance I tried that quick-ng-repeat directive and it seemed to speed up some of the passage rendering, but the initial iPad app load seems to be really slow.

**Comment by wlaurance** [comment]
Yeah we definitely need an optimization pass. We have a lot load in the <head></head> that doesn't need to be.

**Comment by kriskelly** [comment]
@wlaurance I'm taking a crack at rewriting the `input` as a directive using jqLite for the events, to see if that helps.

**Comment by kriskelly** [comment]
@wlaurance Here's a PR for refactoring that input, I think it helps a bit but still doesn't solve the problem of the slow page loads.

https://github.com/empirical-org/Quill-Grammar/pull/153

I think the slow page loads might be a lot due to the large size of the JS. Even on prod, the LMS JS file is 1.5mb and takes over 10s to load in Chrome for me right now, and the iframe JS doesn't even start loading until after that's finished.

**Comment by kriskelly** [comment]
@elliotmandel Would you mind checking the performance of the app on your iPad on staging and see if it's acceptable now?

**Comment by kriskelly** [comment]
It still takes awhile to load but it seems like maybe it runs a bit smoother since I merged #153

**Comment by tomcalabrese** [comment]
Tested on my iPad and the proofreader passages still don't appear.

You can see a video record here here: https://youtu.be/bycuiSoG0Ws

**Comment by petergault** [comment]
@ddmck @tomcalabrese As a test for this, see if it is working for Tom.

**Comment by ddmck** [comment]
Confirmed to be working and faster than before on Toms iPad.
